feature(ui-ux) added dvm evm designs for onboarding
BirthdayResearch/defichain-wallet pull request #3983
Opened 2023-06-28 03:33 UTC by nattadex

#### What this PR does / why we need it:

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode\*
- [ ] Your UI implementation visually matched the rendered design\*
- [ ] Unit tests\*
- [ ] Added e2e tests\*
- [ ] Added translations\*

2023-07-06 03:02 UTC, lykalabrada requested changes

2023-07-06 03:02 UTC, lykalabrada commented on mobile-app/app/screens/WalletNavigator/screens/components/OnboardingCarousel.tsx
>  ];
Right side of the image is a little bit cropped
<img width="767" alt="image" src="https://github.com/BirthdayResearch/defichain-wallet/assets/17063281/944d37b8-c32f-4036-af21-ce4e43603123">

2023-07-06 04:56 UTC, fullstackninja864 requested changes

2023-07-06 04:56 UTC, fullstackninja864 commented on mobile-app/app/screens/WalletNavigator/screens/CreateWallet/CreateWalletGuidelines.tsx
> +              {g.icon ? (
For consistency can we do ?

```
interface GuidelineItem {
  title: string;
  Icon?: () => JSX.Element
}

2023-07-06 04:56 UTC, fullstackninja864 commented on shared/translations/languages/zh-Hant.json
> +    "EVM compatible":"EVM compatible",
```suggestion
    "EVM compatible": "EVM compatible",
```

2023-07-06 04:56 UTC, fullstackninja864 commented on shared/translations/languages/zh-Hant.json
> +    "Seamless transfers between DeFiChain and MetaChain via generated EVM address.":"Seamless transfers between DeFiChain and MetaChain via generated EVM address.",
```suggestion
    "Seamless transfers between DeFiChain and MetaChain via generated EVM address.": "Seamless transfers between DeFiChain and MetaChain via generated EVM address.",
```

2023-07-06 04:56 UTC, fullstackninja864 commented on shared/translations/languages/zh-Hant.json
> +    "A mapped EVM address will be generated to ensure seamless transfers between DeFiChain and MetaChain.":"A mapped EVM address will be generated to ensure seamless transfers between DeFiChain and M
```suggestion
    "A mapped EVM address will be generated to ensure seamless transfers between DeFiChain and MetaChain.": "A mapped EVM address will be generated to ensure seamless transfers between DeFiChain and MetaChain."
```

2023-07-06 04:56 UTC, fullstackninja864 commented on shared/translations/languages/zh-Hans.json
> +    "A mapped EVM address will be generated to ensure seamless transfers between DeFiChain and MetaChain.":"A mapped EVM address will be generated to ensure seamless transfers between DeFiChain and M
```suggestion
    "A mapped EVM address will be generated to ensure seamless transfers between DeFiChain and MetaChain.": "A mapped EVM address will be generated to ensure seamless transfers between DeFiChain and MetaChain."
```

2023-07-06 04:56 UTC, fullstackninja864 commented on shared/translations/languages/zh-Hans.json
> +    "Seamless transfers between DeFiChain and MetaChain via generated EVM address.":"Seamless transfers between DeFiChain and MetaChain via generated EVM address.",
```suggestion
    "Seamless transfers between DeFiChain and MetaChain via generated EVM address.": "Seamless transfers between DeFiChain and MetaChain via generated EVM address.",
```

2023-07-06 04:56 UTC, fullstackninja864 commented on shared/translations/languages/zh-Hans.json
> +    "EVM compatible":"EVM compatible",
```suggestion
    "EVM compatible": "EVM compatible",
```

2023-07-06 04:56 UTC, fullstackninja864 commented on shared/translations/languages/it.json
> +    "A mapped EVM address will be generated to ensure seamless transfers between DeFiChain and MetaChain.":"A mapped EVM address will be generated to ensure seamless transfers between DeFiChain and M
```suggestion
    "A mapped EVM address will be generated to ensure seamless transfers between DeFiChain and MetaChain.": "A mapped EVM address will be generated to ensure seamless transfers between DeFiChain and MetaChain."
```

2023-07-06 04:56 UTC, fullstackninja864 commented on shared/translations/languages/it.json
> +    "Seamless transfers between DeFiChain and MetaChain via generated EVM address.":"Seamless transfers between DeFiChain and MetaChain via generated EVM address.",
```suggestion
    "EVM compatible": "EVM compatible",
    "Seamless transfers between DeFiChain and MetaChain via generated EVM address.": "Seamless transfers between DeFiChain and MetaChain via generated EVM address.",
```

2023-07-06 04:56 UTC, fullstackninja864 commented on shared/translations/languages/fr.json
> +    "A mapped EVM address will be generated to ensure seamless transfers between DeFiChain and MetaChain.":"Une adresse EVM mappée sera générée pour assurer des transferts transparents entre DeFiChai
```suggestion
    "A mapped EVM address will be generated to ensure seamless transfers between DeFiChain and MetaChain.": "Une adresse EVM mappée sera générée pour assurer des transferts transparents entre DeFiChain et MetaChain.",
```

2023-07-06 04:56 UTC, fullstackninja864 commented on shared/translations/languages/fr.json
> +    "Seamless transfers between DeFiChain and MetaChain via generated EVM address.":"Transferts transparents entre DeFiChain et MetaChain via l'adresse EVM générée.",
```suggestion
    "EVM compatible": "Compatible EVM",
    "Seamless transfers between DeFiChain and MetaChain via generated EVM address.": "Transferts transparents entre DeFiChain et MetaChain via l'adresse EVM générée.",
```

2023-07-06 04:56 UTC, fullstackninja864 commented on shared/translations/languages/es.json
> +    "A mapped EVM address will be generated to ensure seamless transfers between DeFiChain and MetaChain.":"A mapped EVM address will be generated to ensure seamless transfers between DeFiChain and M
```suggestion
    "A mapped EVM address will be generated to ensure seamless transfers between DeFiChain and MetaChain.": "A mapped EVM address will be generated to ensure seamless transfers between DeFiChain and MetaChain."
```

2023-07-06 04:56 UTC, fullstackninja864 commented on shared/translations/languages/es.json
> +    "Seamless transfers between DeFiChain and MetaChain via generated EVM address.":"Seamless transfers between DeFiChain and MetaChain via generated EVM address.",
```suggestion
    "EVM compatible": "EVM compatible",
    "Seamless transfers between DeFiChain and MetaChain via generated EVM address.": "Seamless transfers between DeFiChain and MetaChain via generated EVM address.",
```

2023-07-06 04:56 UTC, fullstackninja864 commented on shared/translations/languages/de.json
> +    "A mapped EVM address will be generated to ensure seamless transfers between DeFiChain and MetaChain.":"Eine zugeordnete EVM-Adresse wird generiert, um eine nahtlose Übertragung zwischen DeFiChai
```suggestion
    "A mapped EVM address will be generated to ensure seamless transfers between DeFiChain and MetaChain.": "Eine zugeordnete EVM-Adresse wird generiert, um eine nahtlose Übertragung zwischen DeFiChain und MetaChain zu gewährleisten."
```

2023-07-06 04:56 UTC, fullstackninja864 commented on shared/translations/languages/de.json
> +    "Seamless transfers between DeFiChain and MetaChain via generated EVM address.":"Nahtlose Übertragung zwischen DeFiChain und MetaChain durch generierte EVM-Adresse.",
```suggestion
    "EVM compatible": "EVM-kompatibel",
    "Seamless transfers between DeFiChain and MetaChain via generated EVM address.": "Nahtlose Übertragung zwischen DeFiChain und MetaChain durch generierte EVM-Adresse.",
```

2023-07-06 06:08 UTC, fullstackninja864 commented on mobile-app/app/screens/WalletNavigator/screens/CreateWallet/CreateWalletGuidelines.tsx
> +    },
```suggestion
    Icon: (): JSX.Element => (
        <ThemedIcon
          light={tailwind("text-mono-light-v2-100")}
          dark={tailwind("text-mono-dark-v2-100")}
          iconType="Feather"
          name="edit-2"
          size={14}
        />
      ),
```

2023-07-06 09:27 UTC, fullstackninja864 approved these changes

2023-07-06 09:29 UTC, lykalabrada approved these changes

2023-07-11 06:19 UTC, thedoublejay approved these changes

2023-07-11 06:19 UTC, merged